# Generated by Django 5.0.1 on 2024-02-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Codigo4',
            new_name='codigo_postal',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Direccion1',
            new_name='direccion_principal',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Direccion2',
            new_name='direccion_secundaria',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Iniciar',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Referido',
            new_name='referencia',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Telefono3',
            new_name='telefono_emergencia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Ingles',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel_ingles',
            field=models.CharField(blank=True, choices=[('nulo', 'nulo'), ('basico', 'basico'), ('medio', 'medio'), ('avanzado', 'avanzado'), ('nativo', 'nativo')], max_length=255, null=True, verbose_name='Nivel de Inglés'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Cargo1',
            field=models.CharField(blank=True, choices=[('Limpieza', 'Limpieza'), ('Mantenimiento', 'Mantenimiento'), ('Ayudante-cocina', 'Ayudante-cocina'), ('Recepcion', 'Recepcion')], max_length=255, null=True, verbose_name='Cargo Deseado 1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Cargo2',
            field=models.CharField(blank=True, choices=[('Limpieza', 'Limpieza'), ('Mantenimiento', 'Mantenimiento'), ('Ayudante-cocina', 'Ayudante-cocina'), ('Recepcion', 'Recepcion')], max_length=255, null=True, verbose_name='Cargo Deseado 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Conociste',
            field=models.CharField(blank=True, choices=[('referencia', 'referencia'), ('sticker-qr', 'sticker-qr'), ('volante', 'volante'), ('oficina', 'oficina'), ('google', 'google'), ('otro', 'otro')], max_length=255, null=True, verbose_name='Cómo nos Conociste'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Transporte',
            field=models.CharField(blank=True, choices=[('bus', 'bus'), ('vehiculo-propio', 'vehiculo-propio'), ('uber', 'uber'), ('OTRO', 'OTRO')], max_length=255, null=True, verbose_name='Transporte Utilizado'),
        ),
    ]
