# Generated by Django 5.0.1 on 2024-01-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cargo_deseado1',
            new_name='Cargo1',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='cargo_deseado2',
            new_name='Cargo2',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='ciudad',
            new_name='Ciudad',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='como_nos_conociste',
            new_name='Conociste',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='direccion1',
            new_name='Direccion1',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='direccion2',
            new_name='Direccion2',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='estado_provincia',
            new_name='Estado_Provincia',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nivel_ingles',
            new_name='Ingles',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_inicio',
            new_name='Iniciar',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='referido_por',
            new_name='Referido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono1',
            new_name='Telefono1',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono2',
            new_name='Telefono2',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono3',
            new_name='Telefono3',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='transporte_utilizado',
            new_name='Transporte',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_nacimiento',
            new_name='fechaNacimiento',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='identificacion',
            new_name='formFile',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='hoja_vida',
            new_name='formFile2',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='turno_deseado',
            new_name='turno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='codigo_postal',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Codigo1',
            field=models.CharField(default='507', max_length=20, verbose_name='Codigo1'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Codigo2',
            field=models.CharField(default='507', max_length=20, verbose_name='Codigo2'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Codigo3',
            field=models.CharField(default='507', max_length=20, verbose_name='Codigo3'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Codigo4',
            field=models.CharField(default='507', max_length=20, verbose_name='Codigo4'),
        ),
    ]
