# Generated by Django 5.0.1 on 2024-01-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_rename_cargo_deseado1_usuario_cargo1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fechaNacimiento',
            new_name='fecha_nacimiento',
        ),
    ]
