# Generated by Django 5.0.1 on 2024-02-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_rename_codigo4_usuario_codigo_postal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='formFile2',
            new_name='cv_file',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='formFile',
            new_name='id_file',
        ),
    ]
