# Generated by Django 5.0.1 on 2024-02-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_rename_formfile2_usuario_cv_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='turno',
            field=models.CharField(blank=True, choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche'), ('Madrugada', 'Madrugada')], max_length=255, null=True, verbose_name='Turno Deseado'),
        ),
    ]
