# Generated by Django 5.0.1 on 2024-01-24 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0004_alter_usuario_formfile2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Cargo1',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager')], max_length=255, null=True, verbose_name='Cargo Deseado 1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Cargo2',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager')], max_length=255, null=True, verbose_name='Cargo Deseado 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Ciudad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Codigo1',
            field=models.CharField(blank=True, default='507', max_length=20, null=True, verbose_name='Codigo1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Codigo2',
            field=models.CharField(blank=True, default='507', max_length=20, null=True, verbose_name='Codigo2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Codigo3',
            field=models.CharField(blank=True, default='507', max_length=20, null=True, verbose_name='Codigo3'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Conociste',
            field=models.CharField(blank=True, choices=[('Redes sociales', 'Redes sociales')], max_length=255, null=True, verbose_name='Cómo nos Conociste'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Direccion1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección 1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Direccion2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Estado_Provincia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado/Provincia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Ingles',
            field=models.CharField(blank=True, choices=[('Avanzado', 'Avanzado'), ('Intermedio', 'Intermedio'), ('Principiante', 'Principiante')], max_length=255, null=True, verbose_name='Nivel de Inglés'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Telefono1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Telefono2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Telefono3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 3'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Transporte',
            field=models.CharField(blank=True, choices=[('Transporte publico', 'Transporte público')], max_length=255, null=True, verbose_name='Transporte Utilizado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='alergia',
            field=models.TextField(blank=True, null=True, verbose_name='Alergia o Discapacidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='formFile2',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Hoja de Vida'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otros', 'Otros')], max_length=255, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[('Panama', 'Panamá'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Cuba', 'Cuba'), ('Ecuador', 'Ecuador'), ('United-States', 'United States'), ('Guatemala', 'Guatemala'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'), ('Jamaica', 'Jamaica'), ('Mexico', 'Mexico'), ('Nicaragua', 'Nicaragua'), ('Peru', 'Peru'), ('Venezuela', 'Venezuela'), ('Otros', 'Otros')], max_length=255, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Contacto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turno',
            field=models.CharField(blank=True, choices=[('En la mañana', 'En la mañana')], max_length=255, null=True, verbose_name='Turno Deseado'),
        ),
        migrations.CreateModel(
            name='PoliticasAceptadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptadas', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
