# Generated by Django 5.0.1 on 2024-01-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_alter_usuario_cargo1_alter_usuario_cargo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Ciudad',
            field=models.CharField(max_length=255, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Codigo1',
            field=models.CharField(default='507', max_length=20, null=True, verbose_name='Codigo1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Codigo2',
            field=models.CharField(default='507', max_length=20, null=True, verbose_name='Codigo2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Codigo3',
            field=models.CharField(default='507', max_length=20, null=True, verbose_name='Codigo3'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Codigo4',
            field=models.CharField(default='507', max_length=20, null=True, verbose_name='Codigo4'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Direccion1',
            field=models.CharField(max_length=255, null=True, verbose_name='Dirección 1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Direccion2',
            field=models.CharField(max_length=255, null=True, verbose_name='Dirección 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Estado_Provincia',
            field=models.CharField(max_length=255, null=True, verbose_name='Estado/Provincia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Referido',
            field=models.CharField(max_length=255, null=True, verbose_name='Referido por'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Telefono1',
            field=models.CharField(max_length=20, null=True, verbose_name='Teléfono 1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Telefono2',
            field=models.CharField(max_length=20, null=True, verbose_name='Teléfono 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Telefono3',
            field=models.CharField(max_length=20, null=True, verbose_name='Teléfono 3'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=255, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='formFile2',
            field=models.FileField(null=True, upload_to='archivos/', verbose_name='Hoja de Vida'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(choices=[('Panama', 'Panamá'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Cuba', 'Cuba'), ('Ecuador', 'Ecuador'), ('United-States', 'United States'), ('Guatemala', 'Guatemala'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'), ('Jamaica', 'Jamaica'), ('Mexico', 'Mexico'), ('Nicaragua', 'Nicaragua'), ('Peru', 'Peru'), ('Venezuela', 'Venezuela'), ('Otros', 'Otros')], max_length=255, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_contacto',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre de Contacto'),
        ),
    ]
