# Generated by Django 5.0.1 on 2024-02-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_alter_usuario_ciudad_alter_usuario_codigo1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoliticasAceptadas',
        ),
    ]
