# Generated by Django 5.0.1 on 2024-02-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0011_alter_usuario_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=255, null=True, verbose_name='Género'),
        ),
    ]
