# Generated by Django 5.0.1 on 2024-02-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0014_alter_usuario_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Ciudad',
            field=models.CharField(blank=True, default='cid', max_length=255, verbose_name='Ciudad cliente'),
        ),
    ]
