# Generated by Django 5.0.1 on 2024-02-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0015_alter_usuario_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Ciudad',
            new_name='ciudad',
        ),
    ]
