# Generated by Django 5.0.1 on 2024-02-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_user',
            field=models.CharField(default='2540736c178b4212b564a9d0784536bb', max_length=100),
        ),
    ]
