# Generated by Django 5.0.1 on 2024-02-20 14:54

import backend.auth_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0002_alter_user_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_user',
            field=models.CharField(default=backend.auth_users.models.generar_token, max_length=100),
        ),
    ]
