# Generated by Django 5.0.1 on 2024-02-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0003_alter_user_token_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
