# Generated by Django 5.0.1 on 2024-02-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0004_user_token_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_expiration',
        ),
    ]
