# Generated by Django 5.0.1 on 2024-02-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='nombre', max_length=255, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=255, null=True, verbose_name='Género')),
                ('nacionalidad', models.CharField(blank=True, choices=[('Panama', 'Panamá'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Cuba', 'Cuba'), ('Ecuador', 'Ecuador'), ('United-States', 'United States'), ('Guatemala', 'Guatemala'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'), ('Jamaica', 'Jamaica'), ('Mexico', 'Mexico'), ('Nicaragua', 'Nicaragua'), ('Peru', 'Peru'), ('Venezuela', 'Venezuela'), ('Otros', 'Otros')], max_length=255, null=True, verbose_name='Nacionalidad')),
                ('fecha_nacimiento', models.TextField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('alergia', models.TextField(blank=True, null=True, verbose_name='Alergia o Discapacidad')),
                ('id_file', models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Identificación/Pasaporte')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Hoja de Vida')),
                ('Telefono1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 1')),
                ('Telefono2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 2')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 3')),
                ('nombre_contacto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Contacto')),
                ('direccion_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección 1')),
                ('direccion_secundaria', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección 2')),
                ('ciudad', models.CharField(blank=True, default='cid', max_length=255, verbose_name='Ciudad cliente')),
                ('Estado_Provincia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado/Provincia')),
                ('Codigo1', models.CharField(blank=True, choices=[('507', '507'), ('1', '1')], default='507', max_length=20, null=True, verbose_name='Codigo1')),
                ('Codigo2', models.CharField(blank=True, choices=[('507', '507'), ('1', '1')], default='507', max_length=20, null=True, verbose_name='Codigo2')),
                ('Codigo3', models.CharField(blank=True, default='507', max_length=20, null=True, verbose_name='Codigo3')),
                ('codigo_postal', models.CharField(blank=True, default='507', max_length=20, null=True, verbose_name='Codigo4')),
                ('Cargo1', models.CharField(blank=True, choices=[('Limpieza', 'Limpieza'), ('Mantenimiento', 'Mantenimiento'), ('Ayudante-cocina', 'Ayudante-cocina'), ('Recepcion', 'Recepcion')], default='nombre', max_length=255, null=True, verbose_name='Cargo Deseado 1')),
                ('Cargo2', models.CharField(choices=[('Limpieza', 'Limpieza'), ('Mantenimiento', 'Mantenimiento'), ('Ayudante-cocina', 'Ayudante-cocina'), ('Recepcion', 'Recepcion')], default='nombre', max_length=255, verbose_name='Cargo Deseado 2')),
                ('turno', models.CharField(blank=True, choices=[('mañana', 'mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche'), ('Madrugada', 'Madrugada')], max_length=255, null=True, verbose_name='Turno Deseado')),
                ('nivel_ingles', models.CharField(blank=True, choices=[('nulo', 'nulo'), ('basico', 'basico'), ('medio', 'medio'), ('avanzado', 'avanzado'), ('nativo', 'nativo')], max_length=255, null=True, verbose_name='Nivel de Inglés')),
                ('fecha_inicio', models.TextField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('Transporte', models.CharField(blank=True, choices=[('bus', 'bus'), ('vehiculo-propio', 'vehiculo-propio'), ('uber', 'uber'), ('OTRO', 'OTRO')], max_length=255, null=True, verbose_name='Transporte Utilizado')),
                ('Conociste', models.CharField(blank=True, choices=[('referencia', 'referencia'), ('sticker-qr', 'sticker-qr'), ('volante', 'volante'), ('oficina', 'oficina'), ('google', 'google'), ('otro', 'otro')], max_length=255, null=True, verbose_name='Cómo nos Conociste')),
                ('referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referido por')),
            ],
            options={
                'verbose_name_plural': 'Formularios de Usuarios',
            },
        ),
    ]
