# Generated by Django 5.0.1 on 2024-02-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parrafo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='nombre', max_length=255, verbose_name='Nombre')),
                ('apellido', models.CharField(default='apellido', max_length=255, verbose_name='Apellido')),
                ('email', models.EmailField(default='email@exampl.ecom', max_length=255, verbose_name='Correo Electrónico')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='genero', max_length=255, verbose_name='Género')),
                ('nacionalidad', models.CharField(choices=[('Panama', 'Panamá'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Cuba', 'Cuba'), ('Ecuador', 'Ecuador'), ('United-States', 'United States'), ('Guatemala', 'Guatemala'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'), ('Jamaica', 'Jamaica'), ('Mexico', 'Mexico'), ('Nicaragua', 'Nicaragua'), ('Peru', 'Peru'), ('Venezuela', 'Venezuela'), ('Otro', 'Otro')], default='507', max_length=255, verbose_name='Nacionalidad')),
                ('fecha_nacimiento', models.DateField(default='2012-12-12', verbose_name='Fecha de Nacimiento')),
                ('alergia', models.TextField(default='alergia', verbose_name='Alergia o Discapacidad')),
                ('id_file', models.FileField(default='id-file', upload_to='archivos/', verbose_name='Identificación/Pasaporte')),
                ('cv_file', models.FileField(default='cv-file', upload_to='archivos/', verbose_name='Hoja de Vida')),
                ('codigo1', models.CharField(choices=[('507', '507'), ('1', '1')], default='codigo1', max_length=20, verbose_name='Codigo1')),
                ('Telefono1', models.IntegerField(default='telefono1', verbose_name='Teléfono 1')),
                ('codigo2', models.CharField(choices=[('507', '507'), ('1', '1')], default='codigo2', max_length=20, verbose_name='Codigo2')),
                ('Telefono2', models.IntegerField(default='telefono2', verbose_name='Teléfono 2')),
                ('codigo3', models.CharField(choices=[('507', '507'), ('1', '1')], default='codigo3', max_length=20, verbose_name='Codigo3')),
                ('telefono_emergencia', models.IntegerField(default='telefono emergencia', verbose_name='Teléfono emergencia')),
                ('nombre_contacto', models.CharField(default='nombre contacto', max_length=255, verbose_name='Nombre de Contacto')),
                ('direccion_principal', models.CharField(default='direccion principal', max_length=255, verbose_name='Dirección principal')),
                ('direccion_secundaria', models.CharField(blank=True, default='direccion secundaria', max_length=255, null=True, verbose_name='Dirección secundaria')),
                ('ciudad', models.CharField(default='ciudad', max_length=255, verbose_name='Ciudad ')),
                ('Estado_Provincia', models.CharField(default='estado/provincia', max_length=255, verbose_name='Estado/Provincia')),
                ('Cargo1', models.CharField(choices=[('Limpieza', 'Limpieza'), ('Mantenimiento', 'Mantenimiento'), ('Ayudante-cocina', 'Ayudante-cocina'), ('Recepcion', 'Recepcion')], default='cargo 1', max_length=255, verbose_name='Cargo Deseado 1')),
                ('Cargo2', models.CharField(choices=[('Limpieza', 'Limpieza'), ('Mantenimiento', 'Mantenimiento'), ('Ayudante-cocina', 'Ayudante-cocina'), ('Recepcion', 'Recepcion')], default='cargo 2', max_length=255, verbose_name='Cargo Deseado 2')),
                ('turno', models.CharField(choices=[('mañana', 'mañana'), ('tarde', 'tarde'), ('noche', 'noche'), ('madrugada', 'madrugada')], default='turno', max_length=255, verbose_name='Turno Deseado')),
                ('nivel_ingles', models.CharField(choices=[('nulo', 'nulo'), ('basico', 'basico'), ('medio', 'medio'), ('avanzado', 'avanzado'), ('nativo', 'nativo')], default='nivel ingles', max_length=255, verbose_name='Nivel de Inglés')),
                ('fecha_inicio', models.DateField(default='2012-12-12', verbose_name='Fecha de Inicio')),
                ('Transporte', models.CharField(choices=[('bus', 'bus'), ('vehiculo-propio', 'vehiculo-propio'), ('uber', 'uber'), ('OTRO', 'OTRO')], default='transporte', max_length=255, verbose_name='Transporte Utilizado')),
                ('Conociste', models.CharField(choices=[('referencia', 'referencia'), ('sticker-qr', 'sticker-qr'), ('volante', 'volante'), ('oficina', 'oficina'), ('google', 'google'), ('otro', 'otro')], default='como nos conociste', max_length=255, verbose_name='Cómo nos Conociste')),
                ('referencia', models.CharField(blank=True, default='referencia', max_length=255, null=True, verbose_name='Referido por')),
            ],
            options={
                'verbose_name_plural': 'Formularios de Usuarios',
            },
        ),
    ]
