# Generated by Django 5.0.1 on 2024-02-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Cargo1',
            field=models.CharField(choices=[('Limpieza', 'Limpieza'), ('Mantenimiento', 'Mantenimiento'), ('Ayudante-cocina', 'Ayudante-cocina'), ('Recepcion', 'Recepcion')], default='cargo 1', max_length=255, verbose_name='Cargo Deseado 1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Cargo2',
            field=models.CharField(choices=[('Limpieza', 'Limpieza'), ('Mantenimiento', 'Mantenimiento'), ('Ayudante-cocina', 'Ayudante-cocina'), ('Recepcion', 'Recepcion')], default='cargo 2', max_length=255, verbose_name='Cargo Deseado 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Conociste',
            field=models.CharField(choices=[('referencia', 'referencia'), ('sticker-qr', 'sticker-qr'), ('volante', 'volante'), ('oficina', 'oficina'), ('google', 'google'), ('otro', 'otro')], default='como nos conociste', max_length=255, verbose_name='Cómo nos Conociste'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Estado_Provincia',
            field=models.CharField(default='estado/provincia', max_length=255, verbose_name='Estado/Provincia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Telefono1',
            field=models.IntegerField(default='telefono1', verbose_name='Teléfono 1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Telefono2',
            field=models.IntegerField(default='telefono2', verbose_name='Teléfono 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Transporte',
            field=models.CharField(choices=[('bus', 'bus'), ('vehiculo-propio', 'vehiculo-propio'), ('uber', 'uber'), ('OTRO', 'OTRO')], default='transporte', max_length=255, verbose_name='Transporte Utilizado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='alergia',
            field=models.TextField(default='alergia', verbose_name='Alergia o Discapacidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='apellido', max_length=255, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default='ciudad', max_length=255, verbose_name='Ciudad '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo1',
            field=models.CharField(choices=[('507', '507'), ('1', '1')], default='codigo1', max_length=20, verbose_name='Codigo1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo2',
            field=models.CharField(choices=[('507', '507'), ('1', '1')], default='codigo2', max_length=20, verbose_name='Codigo2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo3',
            field=models.CharField(choices=[('507', '507'), ('1', '1')], default='codigo3', max_length=20, verbose_name='Codigo3'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cv_file',
            field=models.FileField(default='cv-file', upload_to='archivos/', verbose_name='Hoja de Vida'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion_principal',
            field=models.CharField(default='direccion principal', max_length=255, verbose_name='Dirección principal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion_secundaria',
            field=models.CharField(blank=True, default='direccion secundaria', max_length=255, null=True, verbose_name='Dirección secundaria'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='email@exampl.ecom', max_length=255, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='genero', max_length=255, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_file',
            field=models.FileField(default='id-file', upload_to='archivos/', verbose_name='Identificación/Pasaporte'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel_ingles',
            field=models.CharField(choices=[('nulo', 'nulo'), ('basico', 'basico'), ('medio', 'medio'), ('avanzado', 'avanzado'), ('nativo', 'nativo')], default='nivel ingles', max_length=255, verbose_name='Nivel de Inglés'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='nombre', max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_contacto',
            field=models.CharField(default='nombre contacto', max_length=255, verbose_name='Nombre de Contacto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='referencia',
            field=models.CharField(blank=True, default='referencia', max_length=255, null=True, verbose_name='Referido por'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_emergencia',
            field=models.IntegerField(default='telefono emergencia', verbose_name='Teléfono emergencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turno',
            field=models.CharField(choices=[('mañana', 'mañana'), ('tarde', 'tarde'), ('noche', 'noche'), ('madrugada', 'madrugada')], default='turno', max_length=255, verbose_name='Turno Deseado'),
        ),
    ]
