# Generated by Django 5.0.1 on 2024-02-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Cargo1',
            field=models.CharField(blank=True, choices=[('Limpieza', 'Limpieza'), ('Mantenimiento', 'Mantenimiento'), ('Ayudante-cocina', 'Ayudante-cocina'), ('Recepcion', 'Recepcion')], default='nombre', max_length=255, null=True, verbose_name='Cargo Deseado 1'),
        ),
    ]
