# Generated by Django 5.0.1 on 2024-02-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Codigo3',
            field=models.CharField(blank=True, choices=[('507', '507'), ('1', '1')], default='507', max_length=20, null=True, verbose_name='Codigo3'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='valor default', max_length=255, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, default='cid', max_length=255, verbose_name='Ciudad '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_postal',
            field=models.CharField(blank=True, default='507', max_length=20, null=True, verbose_name='Codigo postal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección principal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion_secundaria',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección secundaria'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono emergencia'),
        ),
    ]
