# Generated by Django 5.0.1 on 2024-03-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_alter_usuario_cargo1_alter_usuario_cargo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Transporte',
            field=models.CharField(choices=[('bus', 'bus'), ('vehiculo-propio', 'vehiculo-propio'), ('uber', 'uber'), ('otro', 'otro')], default='transporte', max_length=255, verbose_name='Transporte Utilizado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cv_file',
            field=models.FileField(default='cv-file', upload_to='media/cv_usuarios/', verbose_name='Hoja de Vida'),
        ),
    ]
