# Generated by Django 5.0.1 on 2024-03-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_alter_usuario_id_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_file',
            field=models.FileField(default='id-file', upload_to='media/id_usuarios', verbose_name='Identificación/Pasaporte'),
        ),
    ]
